

# docker/promtail.yml
# Grafana Loki 로그 수집 설정 (필요 시 수정)
server:
  http_listen_port: 3100
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.internal.dev.moyeobab.com:3100/loki/api/v2/push

scrape_configs:
  - job_name: recommend
    static_configs:
      - targets:
          - localhost
        labels:
          job: recommend
          __path__: /var/log/*.log
